[".submodules/tmux-resurrect"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/tmux-ssh-host"]
    type = "archive"
    url = "https://github.com/yuuan/tmux-ssh-host/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/tmux-yank"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-yank/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-airline"]
    type = "archive"
    url = "https://github.com/vim-airline/vim-airline/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-airline-themes"]
    type = "archive"
    url = "https://github.com/vim-airline/vim-airline-themes/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-ctrlp"]
    type = "archive"
    url = "https://github.com/ctrlpvim/ctrlp.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-fugitive"]
    type = "archive"
    url = "https://github.com/tpope/vim-fugitive/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-gitgutter"]
    type = "archive"
    url = "https://github.com/airblade/vim-gitgutter/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-gnupg"]
    type = "archive"
    url = "https://github.com/jamessan/vim-gnupg/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-jellybeans"]
    type = "archive"
    url = "https://github.com/nanotech/jellybeans.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{if .work -}}
[".submodules/vim-puppet"]
    type = "archive"
    url = "https://github.com/rodjek/vim-puppet/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{- end}}
[".submodules/vim-syntastic"]
    type = "archive"
    url = "https://github.com/vim-syntastic/syntastic/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/vim-tagbar"]
    type = "archive"
    url = "https://github.com/majutsushi/tagbar/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/zsh-powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".submodules/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
